name: tv-recorder
services:
  mirakc:
    image: docker.io/mirakc/mirakc:3.4.1-alpine
    init: true
    restart: unless-stopped
    devices:
      # PLEX PX-S1UD / PLEX PX-Q1UD
      #- /dev/dvb/adapter0
      #- /dev/dvb/adapter1
      #- /dev/dvb/adapter2
      #- /dev/dvb/adapter3
      # PLEX PX-W3U4
      - /dev/px4video0
      - /dev/px4video1
      - /dev/px4video2
      - /dev/px4video3
    ports:
      - 40772:40772
    volumes:
      - type: bind
        source: ./mirakc/config/config.yml
        target: /etc/mirakc/config.yml
        read_only: true
      - type: bind
        source: ./mirakc/docs
        target: /var/www/docs
        read_only: true
      - type: volume
        source: mirakc-epg
        target: /var/lib/mirakc/epg
      - type: bind
        source: ${RECORDING_DIR}
        target: /var/lib/mirakc/recording
    environment:
      TZ: Asia/Tokyo
      RUST_LOG: info
  b25-server:
    image: docker.io/collelog/b25-server:latest-alpine-rpi4-64
    ports:
      - 40773:40773
      - 40774:40774
    devices:
      - /dev/bus/usb
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        VERSION: ${UI_VERSION:-0.5.11}
    ports:
      - ${UI_PORT:-5000}:8000
    volumes:
      - type: bind
        source: ./ui/data
        target: /app/data
    environment:
      MIRAKC_API_URL: http://mirakc:40772/api
      BASE_PATH: /mirakc-ui
      KV_FILEPATH: /app/data/kv.sqlite
      VAPID_SUBJECT: ${VAPID_SUBJECT}
volumes:
  mirakc-epg:
    name: mirakc_epg
    driver: local
