server:
  addrs:
    - http: "0.0.0.0:40772"
  mounts:
    /docs:
      path: "/var/www/docs"
      index: "index.html"

channels:
  - name: ＮＨＫ総合
    type: GR
    channel: "27"
  - name: ＮＨＫＥテレ
    type: GR
    channel: "26"
  - name: 日テレ
    type: GR
    channel: "25"
  - name: ＴＢＳ
    type: GR
    channel: "22"
  - name: フジテレビ
    type: GR
    channel: "21"
  - name: テレビ朝日
    type: GR
    channel: "24"
  - name: テレビ東京
    type: GR
    channel: "23"
  - name: ＴＯＫＹＯ　ＭＸ
    type: GR
    channel: "16"

tuners:
  # PLEX PX-S1UD
  #- name: PX-S1UD
  #  types:
  #    - GR
  #  command: recdvb --strip --dev 0 {{{channel}}} - -

  # PLEX PX-Q1UD
  #- name: PX-Q1UD_0
  #  types:
  #    - GR
  #  command: recdvb --strip --dev 0 {{{channel}}} - -
  #- name: PX-Q1UD_1
  #  types:
  #    - GR
  #  command: recdvb --strip --dev 1 {{{channel}}} - -
  #- name: PX-Q1UD_2
  #  types:
  #    - GR
  #  command: recdvb --strip --dev 2 {{{channel}}} - -
  #- name: PX-Q1UD_3
  #  types:
  #    - GR
  #  command: recdvb --strip --dev 3 {{{channel}}} - -

  # PLEX PX-W3U4
  - name: PX-W3U4_0
    types:
      - BS
      - CS
    command: recpt1 --device /dev/px4video0 {{{channel}}} - -
  - name: PX-W3U4_1
    types:
      - BS
      - CS
    command: recpt1 --device /dev/px4video1 {{{channel}}} - -
  - name: PX-W3U4_2
    types:
      - GR
    command: recpt1 --device /dev/px4video2 {{{channel}}} - -
  - name: PX-W3U4_3
    types:
      - GR
    command: recpt1 --device /dev/px4video3 {{{channel}}} - -

epg:
  cache-dir: /var/lib/mirakc/epg

filters:
  decode-filter:
    command: >-
      socat - tcp-connect:b25-server:40773

recording:
  basedir: /var/lib/mirakc/recording
